### PR TITLE
i18n support

### PR DESCRIPTION
**Pull request by Nats-ji**
I think it's ready for merge. Need someone to review it.

- `protocols.lua` should not contain anything strings for display anymore, but only string ids for i18n to identify.
- The actual strings for display should go inside `lang/en.lua`
- To add a new language just delicate `lang/en.lua` and rename it (e.g. `de.lua`) and edit the table name as well (e.g. `de = { }`)
- And add it into the language list `lang/lang.lua` (e.g. `{ id = "de", name = "Deutsche (German)"}`)

### CODE REVIEW

**Comment by ghost** [comment]
The `protocols.lua` from this branch doesn't seem to have merged with this: 
https://github.com/WolvenKit/BraindanceProtocol/pull/58

Which also means, that the individial translation `.lua` (cn, da, de, en) files will probably need the new strings from `protocols.lua`.

**Edit:**
Also, is there any easy way to sync the individual language files? 

If I, for an example, decide to add more functions to the `protocols.lua`, what is the easiest way to get the new protocols added to all the language files? (or is the proper solution to do it manually?)

**Comment by Nats-ji** [comment]
> The `protocols.lua` from this branch doesn't seem to have merged with this:
> #58

Looks like I missed `Teleport_GenericTheAtlantis` when I manually merged. I believe it's now fixed.

> Also, is there any easy way to sync the individual language files?

I need to edit the script that I used to create the language files. So it can also be used to update them.
Otherwise, it will be a pain to update them manually.

**Comment by ghost** [comment]
I have a few new features waiting to get merged:
https://github.com/VP-EN/BraindanceProtocol/tree/new-features-v2

Kind of wondering if I should wait, or if it's OK with you to just merge the new protocols.

I guess it depends on how far you are with your "language update script" though 👍

**Review by osulli — APPROVED** [review]
LGTM

**Comment by osulli** [comment]
@VP-EN #63

**Pull request merged**
