### PR TITLE
Adding teleport.lua (teleporting locations) + individual vehicle selection

### PR DESCRIPTION
**Pull request by ghost**
Added a lot of teleporting locations.
Divided into multiple categories, since the list of locations became quite long.

All the locations work in-game.

### CODE REVIEW

**Review by osulli — COMMENTED** [review]
LGTM.

BD.lua is updated.
Fairly sure protocols.lua needs updating for it to appear in the GUI.

**Comment by ghost** [comment]
I did update the protocols.lua:
Both here:
https://github.com/WolvenKit/BraindanceProtocol/pull/50/commits/043c218d0635730f9af1cee003c9c68779e680a0#diff-9b2216a2b3a25102c2aaa1fa6438e21df180831dbcaa3ea407782c434f8c194e

Here (formatting):
https://github.com/WolvenKit/BraindanceProtocol/pull/50/commits/bb44e5dc476e1afebb003240a120b182551103d3#diff-9b2216a2b3a25102c2aaa1fa6438e21df180831dbcaa3ea407782c434f8c194e

and here:
https://github.com/WolvenKit/BraindanceProtocol/pull/50/commits/bee3dd300955f60be31526b39d6f8f98ff86792a#diff-9b2216a2b3a25102c2aaa1fa6438e21df180831dbcaa3ea407782c434f8c194e

 Everything shows up ingame (and in the GUI) :)
I tested most teleporting locations and tested a few of the cars I didn't already have in a savegame. Everything seems to work just fine 👍

**Review by ghost — COMMENTED** [review]
Formatting

**Comment by osulli** [comment]
Ah brill - thanks. Missed it as it was collapsed file at the bottom.

**Pull request merged**
